In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotVisibleException,ElementClickInterceptedException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options
import re
import time
import warnings
import requests

warnings.filterwarnings("ignore")

# Answer: 1-

In [2]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [4]:
rank=[]
name=[]
artist=[]
upload_date=[]
views=[]

rank_tag=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
try:
    for i in rank_tag[0:30]:
        rank.append(i.text)
except NoSuchElementException:
    rank.append("-")
except ElementNotVisibleException:
    rank.append("--")
    
name_tag=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
try:
    for i in name_tag[0:30]:
        v_name=i.text.split('[')
        name.append(v_name[0])
except NoSuchElementException:
    name.append("-")
except ElementNotVisibleException:
    name.append("--")
    
artist_tag=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
try:
    for i in artist_tag[0:30]:
        artist.append(i.text)
except NoSuchElementException:
    artist.append("-")
    
date_tag=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
try:
    for i in date_tag[0:30]:
        upload_date.append(i.text)
except NoSuchElementException:
    upload_date.append("-")
    
view_tag=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
try:
    for i in view_tag[0:30]:
        views.append(i.text)
except NoSuchElementException:
    views.append("-")

In [5]:
most_viewed=pd.DataFrame({'Rank':rank,'Video Name':name,'Artist':artist,'Upload Date':upload_date,'Views(Billions)':views})
most_viewed

,Rank,Video Name,Artist,Upload Date,Views(Billions)
0,1.,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.27
1,2.,"""Despacito""",Luis Fonsi,"January 12, 2017",8.08
2,3.,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.61
3,4.,"""Bath Song""",Cocomelon – Nursery Rhymes,"May 2, 2018",6.01
4,5.,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.91
5,6.,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.78
6,7.,"""Phonics Song with Two Words""",ChuChu TV,"March 6, 2014",5.15
7,8.,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,"May 24, 2018",4.92
8,9.,"""Uptown Funk""",Mark Ronson,"November 19, 2014",4.83
9,10.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,"February 27, 2018",4.81
10,11.,"""Gangnam Style""",Psy,"July 15, 2012",4.69
11,12.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,"January 31, 2012",4.53
12,13.,"""Dame Tu Cosita""",El Chombo,"April 5, 2018",4.23
13,14.,"""Sugar""",Maroon 5,"January 14, 2015",3.82
14,15.,"""Axel F""",Crazy Frog,"June 16, 2009",3.75
15,16.,"""Roar""",Katy Perry,"September 5, 2013",3.73
16,17.,"""Counting Stars""",OneRepublic,"May 31, 2013",3.72
17,18.,"""Sorry""",Justin Bieber,"October 22, 2015",3.63
18,19.,"""Thinking Out Loud""",Ed Sheeran,"October 7, 2014",3.55
19,20.,"""Baa Baa Black Sheep""",Cocomelon – Nursery Rhymes,"June 25, 2018",3.49
20,21.,"""Waka Waka (This Time for Africa)""",Shakira,"June 4, 2010",3.47
21,22.,"""Dark Horse""",Katy Perry,"February 20, 2014",3.45
22,23.,"""Faded""",Alan Walker,"December 3, 2015",3.40
23,24.,"""Let Her Go""",Passenger,"July 25, 2012",3.38
24,25.,"""Girls Like You""",Maroon 5,"May 31, 2018",3.37
25,26.,"""Perfect""",Ed Sheeran,"November 9, 2017",3.37
26,27.,"""Bailando""",Enrique Iglesias,"April 11, 2014",3.33
27,28.,"""Lean On""",Major Lazer,"March 22, 2015",3.33
28,29.,"""Humpty the train on a fruits ride""",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.30
29,30.,"""Lakdi Ki Kathi""",Jingle Toons,"June 14, 2018",3.30

In [6]:
driver.close()

# Answer: 2-

In [7]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://www.bcci.tv'
driver.get(url)

In [10]:
#Getting to international fixtures page
i_f = driver.find_element(By.XPATH,"//li[@class='nav-item']")
try:
    i_f.click()
except ElementNotInteractableException:
    driver.get(i_f.get_attribute('href'))  
time.sleep(2)

#scraping match time data
Time = []
times=driver.find_elements(By.XPATH,"//h5[@class='text-right ng-binding']")
for i in times:
    if i.text is None :
        Time.append("Not available") 
    else:
        Time.append(i.text)

#Initializing empty lists
title=[] 
series=[]
place=[]
date=[]
Time = []

#Scraping series title data
seriess=driver.find_elements(By.XPATH,"//div[@class='fixture-card-top']/h5[2]/span")
series = [i.text for i in seriess]
#Scraping match date data
dates=driver.find_elements(By.XPATH,"//div[@class='match-card-left match-schedule']/h5[1]")
date = [i.text for i in dates]
#Scraping match place data
places=driver.find_elements(By.XPATH,"//div[@class='fix-place ng-binding ng-scope']")
place = [i.text for i in places]
#Scraping match title data
titles=driver.find_elements(By.XPATH,"//div[@class='fixture-card-mid d-flex align-items-center justify-content-between']")
title = [i.text.replace('\n',' ') for i in titles]
#Scraping match time data
Times=driver.find_elements(By.XPATH,"//h5[@class='text-right ng-binding']")
Time = [i.text for i in Times]

#creating data frame
df=pd.DataFrame({"Match":title,"Series":series,"Place":place,"Date":date,"Time":Time})
#Displaying data frame
df

,Match,Series,Place,Date,Time
0,India Women vs West Indies Women,ICC WOMENS T20 WORLD CUP 2023,"2nd T20I - Newlands, Cape Town",15 FEB 2023,6:30 PM IST
1,India vs Australia,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"2nd Test - Arun Jaitley Stadium, Delhi",17 FEB 2023,9:30 AM IST
2,England Women vs India Women,ICC WOMENS T20 WORLD CUP 2023,"3rd T20I - St George's Park, Gqeberha",18 FEB 2023,6:30 PM IST
3,India Women vs Ireland Women,ICC WOMENS T20 WORLD CUP 2023,"4th T20I - St George's Park, Gqeberha",20 FEB 2023,6:30 PM IST
4,India vs Australia,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,3rd Test - Himachal Pradesh Cricket Associatio...,1 MAR 2023,9:30 AM IST
5,India vs Australia,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"4th Test - Narendra Modi Stadium, Ahmedabad",9 MAR 2023,9:30 AM IST
6,India vs Australia,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,"1st ODI - Wankhede Stadium, Mumbai",17 MAR 2023,1:30 PM IST
7,India vs Australia,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,2nd ODI - Dr YS Rajasekhara Reddy ACA-VDCA Cri...,19 MAR 2023,1:30 PM IST

In [11]:
driver.close()

# Answer: 3-

In [12]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://www.statisticstimes.com'
driver.get(url)

In [13]:
economy = driver.find_element(By.XPATH,"//*[@id='top']/div[2]/div[2]/button")
try:
    economy.click()
    driver.find_element(By.XPATH,'/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/div[1]/a[3]').click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))
    
time.sleep(3)
try:
    ads=driver.find_element(By.XPATH,'//div[@class="ns-dbyfr-e-19 button-common close-button"]')
    ads.click()
    gdp = driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").click()
except NoSuchElementException:
    driver.get('https://www.statisticstimes.com/economy/india/indian-states-gdp.php')
    
time.sleep(3)


rank=[]
state=[]
GSDP_19_20=[]
GSDP_18_19=[]
share_18_19=[]
GDP_billion=[]


state_rank=driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[1]')
try:
    for i in state_rank:
        rank.append(i.text)
except NoSuchElementException:
    rank.append("-")
    
state_name=driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[2]')
try:
    for i in state_name:
        state.append(i.text)
except NoSuchElementException:
    state.append("-")
        
GSDP_19_20_tag=driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[3]')
try:
    for i in GSDP_19_20_tag:
        GSDP_19_20.append(i.text)
except NoSuchElementException:
    GSDP_19_20.append("-")
    
GSDP_18_19_tag=driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[4]')
try:
    for i in GSDP_18_19_tag:
        GSDP_18_19.append(i.text)
except NoSuchElementException:
    GSDP_18_19.append("-")
    
share_18_19_tag=driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[5]')
try:
    for i in share_18_19_tag:
        share_18_19.append(i.text)
except NoSuchElementException:
    share_18_19.append("-")
    
GDP_billion_tag=driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[6]')
try:
    for i in GDP_billion_tag:
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("-")

In [14]:
StateWise_GDP=pd.DataFrame({'Rank':rank,'State':state,'GSDP 19-20':GSDP_19_20,'GSDP 18-19':GSDP_18_19,'Share 18-19':share_18_19,'GDP billion':GDP_billion})
StateWise_GDP

,Rank,State,GSDP 19-20,GSDP 18-19,Share 18-19,GDP billion
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [15]:
driver.close()

# Answer: 4-

In [16]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://github.com/trending'
driver.get(url)

In [17]:
repo,des,lan = [],[],[]
for i in driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]'):
    repo.append(i.text)
for i in driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]'):
    des.append(i.text)
for i in driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]'):
    lan.append(i.text)

In [18]:
git = pd.DataFrame({'Repository title':repo[0:22], 'Repository description':des[0:22], 'Language used':lan[0:22]})
git

,Repository title,Repository description,Language used
0,acikkaynak / deprem-yardim-backend-go,Wildebeest is an ActivityPub and Mastodon-comp...,Go
1,guaguaguaxia / weekly_report,A WhatsApp client library for NodeJS that conn...,CSS
2,cloudflare / wildebeest,current-front,TypeScript
3,pedroslopez / whatsapp-web.js,"Your self-hosted, globally interconnected micr...",JavaScript
4,acikkaynak / deprem-io-frontend,This repo includes ChatGPT prompt curation to ...,HTML
5,mastodon / mastodon,Reverse engineered API of Microsoft's Bing Chat,Ruby
6,f / awesome-chatgpt-prompts,current back Deprem.io is a platform to help w...,HTML
7,acheong08 / EdgeGPT,Open source virtual / remote desktop infrastru...,Python
8,acikkaynak / deprem-io-backend,An Open Source Financial Switch to make Paymen...,JavaScript
9,rustdesk / rustdesk,📚 Papers & tech blogs by companies sharing the...,Rust
10,juspay / hyperswitch,This is the starting codebase that will be use...,Rust
11,eugeneyan / applied-ml,iOS 14.0-15.7.1 & 16.0-16.1.2 MacDirtyCow ToolBox,JavaScript
12,ExamProCo / aws-bootcamp-cruddur-2023,Scheduling infrastructure for absolutely every...,Swift
13,leminlimez / Cowabunga,Hydrogen is Shopify’s stack for headless comme...,TypeScript
14,calcom / cal.com,"Lenster is a decentralized, and permissionless...",TypeScript
15,Shopify / hydrogen,An enterprise-class low-code technology stack ...,TypeScript
16,lensterxyz / lenster,An unnecessarily tiny implementation of GPT-2 ...,TypeScript
17,alibaba / lowcode-engine,🤗 PEFT: State-of-the-art Parameter-Efficient F...,Python
18,karfly / chatgpt_telegram_bot,Cross-platform Rust rewrite of the GNU coreutils,Python
19,jaymody / picoGPT,Stable Diffusion web UI,Python
20,huggingface / peft,A ChatGPT implementation with support for Bing...,Rust
21,uutils / coreutils,openpilot is an open source driver assistance ...,Python

In [19]:
driver.close()

# Answer: 5-

In [20]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://www.billboard.com'
driver.get(url)

In [23]:
nav=driver.find_element(By.XPATH,"/html/body/div[3]/header/div[1]/div/div/div[1]/button")
nav.click()

time.sleep(5)

#Hot 100 songs
hot_100=driver.find_element(By.XPATH,'/html[1]/body[1]/div[3]/div[6]/div[1]/div[1]/div[1]/ul[1]/li[1]/ul[1]/li[2]/a[1]')
hot_100.click()

Name=[]
Artist=[]
rank=[]

#Scraping name
Name_tag=driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']")
for i in Name_tag:
    Name.append(i.text)

#Scraping artist
Artist_tag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']")
for i in Artist_tag:
    Artist.append(i.text)

#Scraping rank
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
for i in rankTag[:3]:
    rank.append(i.text )
    
#Scraping name
Rank=[]
nameTag=driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
for i in nameTag:
    Name.append(i.text )

#Scraping artist
artistTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
for i in artistTag:
    Artist.append(i.text )

#Scraping rank
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
for i in RankTag:
    Rank.append(i.text)
    
    
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)
        
# slicing Data
last_week_rank=Rank[0::3]
last_week_rank.insert(0,rank[0])
peak_rank=Rank[1::3]
peak_rank.insert(0,rank[1])
weeks_on_board=Rank[2::3]
weeks_on_board.insert(0,rank[2])

# Create Dataframe
songs_top=pd.DataFrame({"Name":Name[:100],"Artist":Artist[:100],"Last Week Rank":last_week_rank[0:100],"Peak Rank":peak_rank[0:100],"Weeks On Board":weeks_on_board[0:100]})
songs_top

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/header/div[1]/div/div/div[1]/button"}
  (Session info: chrome=109.0.5414.121)
Stacktrace:
Backtrace:
	(No symbol) [0x01036643]
	(No symbol) [0x00FCBE21]
	(No symbol) [0x00ECDA9D]
	(No symbol) [0x00F01342]
	(No symbol) [0x00F0147B]
	(No symbol) [0x00F38DC2]
	(No symbol) [0x00F1FDC4]
	(No symbol) [0x00F36B09]
	(No symbol) [0x00F1FB76]
	(No symbol) [0x00EF49C1]
	(No symbol) [0x00EF5E5D]
	GetHandleVerifier [0x012AA142+2497106]
	GetHandleVerifier [0x012D85D3+2686691]
	GetHandleVerifier [0x012DBB9C+2700460]
	GetHandleVerifier [0x010E3B10+635936]
	(No symbol) [0x00FD4A1F]
	(No symbol) [0x00FDA418]
	(No symbol) [0x00FDA505]
	(No symbol) [0x00FE508B]
	BaseThreadInitThunk [0x76157D69+25]
	RtlInitializeExceptionChain [0x7760BB9B+107]
	RtlClearBits [0x7760BB1F+191]

In [24]:
driver.close()

# Answer: 6-

In [25]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)

In [26]:
book_name=[]
author_name=[]
volumes_sold=[]
publisher=[]
genre=[]

b_name=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[2]')
try:
    for i in b_name:
        book_name.append(i.text)
except:
    book_name.append("-")
    
a_name=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[3]')
try:
    for i in a_name:
        author_name.append(i.text)
except:
    author_name.append("-")
    
v_sold=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[4]')
try:
    for i in v_sold:
        volumes_sold.append(i.text)
except:
    volumes_sold.append("-")
    
b_publisher=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[5]')
try:
    for i in b_publisher:
        publisher.append(i.text)
except:
    publisher.append("-")
    
b_genre=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[6]')
try:
    for i in b_genre:
        genre.append(i.text)
except:
    genre.append("-")
    
Highest_selling_novels=pd.DataFrame({'Book Name':book_name,'Author Name':author_name,'Volumes sold':volumes_sold,'Publisher':publisher,'Genre':genre})
Highest_selling_novels

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [27]:
driver.close()

# Answer: 7-

In [28]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://www.imdb.com/list/ls095964455'
driver.get(url)

In [29]:
name=[]
year=[]
genre=[]
run_time=[]
ratings=[]
votes=[]

s_name=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
try:
    for i in s_name:
        name.append(i.text)
except:
    name.append("--") 
    
s_year=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
try:
    for i in s_year:
        year.append(i.text)
except:
    year.append("--")   

s_genre=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')
try:
    for i in s_genre:
        genre.append(i.text)
except:
    genre.append("--")
    
r_time=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')
try:
    for i in r_time:
        run_time.append(i.text)
except:
    run_time.append("--")   

rating=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')
try:
    for i in rating:
        ratings.append(i.text)
except:
    ratings.append("--")
    
vote=driver.find_elements(By.XPATH,'//span[@name="nv"]')
try:
    for i in vote:
        votes.append(i.text)
except:
    votes.append("--")
    
tv_series=pd.DataFrame({'Name':name,'Year Span':year,'Genre':genre,'Run Time':run_time,'Ratings':ratings,'Votes':votes})
tv_series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,123,823"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,8.7,"1,211,621"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,007,325"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"297,202"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"256,119"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,750"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"62,632"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"203,038"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"42,056"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"250,869"

In [30]:
driver.close()

# Answer: 8-

In [31]:
driver=webdriver.Chrome(r"C:\Users\anshu\Downloads\chromedriver_win32\chromedriver.exe")

url = 'https://archive.ics.uci.edu/ml/index.php'
driver.get(url)

In [32]:
#clicking on view all Dataset
Dataset= driver.find_elements(By.XPATH,"//span[@class='normal']/b/a")[0].get_attribute('href')
driver.get(Dataset)

# Scraping dataset
data=[]
try:
    data_tag=driver.find_elements(By.XPATH,"//td//p[@class='normal']")
    for i in data_tag[8:4362]:
        data.append(i.text )
except:
    data.append('-')
    
#slicing dataset
Dataset_name=data[::7]
Data_type=data[1::7]
Task=data[2::7]
Attribute_type=data[3::7]
instances=data[4::7]
attribute=data[5::7]
Year=data[6::7]

#creating Dataframe
Datasets= pd.DataFrame({"Dataset name":Dataset_name,"Data type":Data_type,"Task":Task,"Attribute type":Attribute_type,"Instances":instances,"Attribute":attribute,"Year":Year})
Datasets

,Dataset name,Data type,Task,Attribute type,Instances,Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [33]:
driver.close()